Fix compile on arm
Summary:
Don't ask me why but the defines are giving an ultra weird warning

src/kbkglobal.h:59:26: error: expected ‘,’ or ‘...’ before numeric constant
 #define minZ             1.0 // Nearest point represented in the view.

And the #include "kbkglobal.h" is needed so glColor3f is defined via the includes there

Reviewers: #kde_games, apol

Reviewed By: apol

Subscribers: kde-games-devel, apol

Differential Revision: https://phabricator.kde.org/D20677